Added check to run modules from /lib/modules or run from /usr/bin

diff --git a/misc-modules/module_load b/misc-modules/module_load
--- a/misc-modules/module_load
+++ b/misc-modules/module_load
@@ -21,8 +21,16 @@ else
     group="wheel"
 fi
 
-echo "Load our module, exit on failure"
-insmod ./$module.ko $* || exit 1
+#echo "Load our module, exit on failure"
+#insmod ./$module.ko $* || exit 1
+echo "Attempting to load our module from /usr/bin/$module.ko"
+
+insmod /usr/bin/$module.ko $* || {
+    echo "Failed to load module from /usr/bin/$module.ko. Trying /lib/modules/$(uname -r)/extra/$module.ko"
+    # If the first attempt fails, attempt to load from /lib/modules/$(uname -r)/extra
+    insmod /lib/modules/$(uname -r)/extra/$module.ko $* || exit 1
+}
+
 echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 if [ ! -z ${major} ]; then
diff --git a/scull/scull_load b/scull/scull_load
--- a/scull/scull_load
+++ b/scull/scull_load
@@ -13,7 +13,14 @@ fi
 
 # invoke insmod with all arguments we got
 # and use a pathname, as insmod doesn't look in . by default
-insmod ./$module.ko $* || exit 1
+echo "Attempting to load our module from /usr/bin/$module.ko"
+
+#insmod /usr/bin/$module.ko $* || exit 1
+insmod /usr/bin/$module.ko $* || {
+    echo "Failed to load module from /usr/bin/$module.ko. Trying /lib/modules/$(uname -r)/extra/$module.ko"
+    # If the first attempt fails, attempt to load from /lib/modules/$(uname -r)/extra
+    insmod /lib/modules/$(uname -r)/extra/$module.ko $* || exit 1
+}
 
 # retrieve major number
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
